# Generated by Django 5.2.1 on 2025-05-19 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Genero Literário', max_length=200, unique=True, verbose_name='Genero Literário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Criado em', verbose_name='Data de criação')),
                ('atualizado_em', models.DateTimeField(auto_now=True, help_text='Atualizado em', verbose_name='Data de atualização')),
            ],
            options={
                'verbose_name': 'Genero Literário',
                'verbose_name_plural': 'Generos Literários',
            },
        ),
        migrations.AlterModelOptions(
            name='editora',
            options={'verbose_name': 'Editora', 'verbose_name_plural': 'Editoras'},
        ),
        migrations.AlterField(
            model_name='editora',
            name='atualizado_em',
            field=models.DateTimeField(auto_now=True, help_text='Atualizado em', verbose_name='Data de atualização'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='cnpj',
            field=models.CharField(help_text='Nº do CNPJ', max_length=14, unique=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, help_text='Criado em', verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='editora',
            name='nome',
            field=models.CharField(help_text='Nome da editora', max_length=200, unique=True, verbose_name='Nome'),
        ),
    ]
