# Generated by Django 5.2.1 on 2025-05-19 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_generoliterario_alter_editora_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Título', max_length=200, verbose_name='Título')),
                ('isbn', models.CharField(help_text='ISBN', max_length=14, unique=True, verbose_name='ISBN')),
                ('nota', models.IntegerField(help_text='Avaliação do livro', null=True, verbose_name='Avaliação do livro')),
                ('editora', models.ForeignKey(help_text='Editora', on_delete=django.db.models.deletion.RESTRICT, to='biblioteca.editora', verbose_name='Editora')),
                ('genero_literario', models.ForeignKey(help_text='Genero Literário', on_delete=django.db.models.deletion.RESTRICT, to='biblioteca.generoliterario', verbose_name='Genero Literário')),
            ],
        ),
    ]
