# Generated by Django 5.2.1 on 2025-05-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_livro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='nota',
            field=models.IntegerField(blank=True, help_text='Avaliação do livro', verbose_name='Avaliação do livro'),
        ),
    ]
